### ISSUE TITLE
Fail to build in macOS

### ISSUE THREAD

**Issue by ncihnegn** [crlf0710/tex-rs#1]
LLVM ERROR: Global variable '_ZN3tex12section_027256_LINKME_ELEMENT_set_initial_values_of_key_variables_027217hfa5c10e66de62617E' has an invalid section specifier '__DATA,__SET_INIT_KEYVAR': mach-o section specifier requires a section whose length is between 1 and 16 characters.

**Comment by crlf0710** [comment]
Thanks for the report, this is known issue at https://github.com/dtolnay/linkme/issues/35 . 

This repo is not ready for others yet, and I'll make a workaround for this issue before it is ready.

**Comment by ncihnegn** [comment]
I don't think it is a _linkme_ issue. I replace all **SET_INIT_KEYVAR** w/ **SIK** and it builds.

**Comment by crlf0710** [comment]
On macOS there's limitation on `linkme`-generated linker section name length. If that naming scheme is not changed on `linkme` side, i'll make those variable names shorter within the code. (Actually i have done so for a few variables).

**Comment by crlf0710** [comment]
Fixed in https://github.com/crlf0710/tex-rs/commit/b4650a4f94de90756b76edded9b5bd30ad4ac61b .
